### PR TITLE
chore: use declare module 'vue' to fix type issues

### PR DESCRIPTION
**Pull request by andreasgangso**
### Changes

Use the newer syntax for adding component instance properties. The old syntax has issues on newer versions of vue. See reference.

### References

https://github.com/vuejs/language-tools/issues/4793#issuecomment-2336471084

### CODE REVIEW

**Comment by andreasgangso** [comment]
@tusharpandey13 can you merge this? We have to maintain a fork at the moment

**Review by tusharpandey13 — APPROVED** [review]
lgtm

**Comment by tusharpandey13** [comment]
Hi @andreasgangso it seems looks like your commit is not signed, can you rebase, sign and push again?
Thanks

**Comment by andreasgangso** [comment]
@tusharpandey13 done

**Pull request merged**
